# Generated by Django 4.1.7 on 2023-03-04 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('licence_plate', models.CharField(max_length=10, verbose_name='Licence plate')),
                ('branch', models.CharField(blank=True, max_length=50, null=True, verbose_name='Branch')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_p', to='person.person')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
    ]
